
use crate::ux_model::intent::{UserCommandInit, UserGoal, UserGoalType, UserPromise, UserPromiseType, UserCommandContext, UserWorkspace};
use crate::ux_model::result::{UserResult, UserSummary, UserResultContext, UserLimitation, UserNextStep};
use crate::application::types::{CommandAction, GenericSuccess, GenericPartial, GenericFailure, ApplicationOutcome};
use crate::application::service::{ActionExecutor, ApplicationService};
use crate::application::adapters::ApplicationAdapters;

impl CommandAction for UserCommandInit {
    type Success = GenericSuccess;
    type Partial = GenericPartial;
    type Failure = GenericFailure;
}

impl<A: ApplicationAdapters> ActionExecutor<UserCommandInit> for ApplicationService<A> {
    async fn execute_action(&self, _action: UserCommandInit, context: UserCommandContext) -> ApplicationOutcome<UserCommandInit> {
        // Get workspace root
        let workspace_root = match &context.user_workspace {
            UserWorkspace::Explicit(path) => path.clone(),
            UserWorkspace::Pwd => {
                match std::env::current_dir() {
                    Ok(dir) => dir,
                    Err(e) => {
                        return UserResult::Failure(GenericFailure {
                            promises: vec![
                                UserPromise(UserPromiseType::NeverSilentWrong),
                                UserPromise(UserPromiseType::ErrorsAreActionable),
                            ],
                            summary: UserSummary("Failed to determine workspace root".to_string()),
                            limitations: vec![UserLimitation(format!("Could not read current directory: {}", e))],
                            next_step: UserNextStep(
                                "Run from a valid directory or specify --workspace /path/to/workspace".to_string(),
                            ),
                            context: UserResultContext { command_context: context },
                        });
                    }
                }
            }
        };

        // Detect language
        let language = if workspace_root.join("Cargo.toml").exists() {
            "rust"
        } else if workspace_root.join("package.json").exists() {
            "typescript"
        } else if workspace_root.join("go.mod").exists() {
            "go"
        } else {
            return UserResult::Failure(GenericFailure {
                promises: vec![
                    UserPromise(UserPromiseType::NeverSilentWrong),
                    UserPromise(UserPromiseType::ErrorsAreActionable),
                ],
                summary: UserSummary("Could not detect project language".to_string()),
                limitations: vec![
                    UserLimitation("No Cargo.toml, package.json, or go.mod found".to_string()),
                ],
                next_step: UserNextStep(
                    "Run from a Rust, TypeScript, or Go project root directory".to_string(),
                ),
                context: UserResultContext { command_context: context },
            });
        };

        // Create .typeglass.toml config
        let config_path = workspace_root.join(".typeglass.toml");
        
        if config_path.exists() {
            return UserResult::Success(GenericSuccess {
                goal: UserGoal(UserGoalType::PrepareWorkspace),
                promises: vec![
                    UserPromise(UserPromiseType::NeverSilentWrong),
                    UserPromise(UserPromiseType::FastByDefault),
                ],
                summary: UserSummary("Workspace already initialized".to_string()),
                next_step: Some(UserNextStep(format!("Config file exists at {}", config_path.display()))),
                context: UserResultContext { command_context: context },
            });
        }

        let config_content = format!(
r#"# TypeGlass Configuration
# Generated by 'typeglass init'

[project]
language = "{}"

[cache]
# Cache TTL in seconds (default: 300 = 5 minutes)
ttl = 300

[lsp]
# LSP server timeout in seconds (default: 30)
timeout = 30

# Maximum query depth (default: 10)
max_depth = 10

[output]
# Default output format: human | json
format = "human"
"#,
            language
        );

        match std::fs::write(&config_path, config_content) {
            Ok(_) => {
                UserResult::Success(GenericSuccess {
                    goal: UserGoal(UserGoalType::PrepareWorkspace),
                    promises: vec![
                        UserPromise(UserPromiseType::NeverSilentWrong),
                        UserPromise(UserPromiseType::FastByDefault),
                    ],
                    summary: UserSummary(format!("Workspace initialized (language: {})", language)),
                    next_step: Some(UserNextStep(format!("Created {}", config_path.display()))),
                    context: UserResultContext { command_context: context },
                })
            }
            Err(e) => {
                UserResult::Failure(GenericFailure {
                    promises: vec![
                        UserPromise(UserPromiseType::NeverSilentWrong),
                        UserPromise(UserPromiseType::ErrorsAreActionable),
                    ],
                    summary: UserSummary("Failed to create config file".to_string()),
                    limitations: vec![UserLimitation(format!("IO error: {}", e))],
                    next_step: UserNextStep(
                        format!("Check write permissions on {}", workspace_root.display()),
                    ),
                    context: UserResultContext { command_context: context },
                })
            }
        }
    }
}
